### ISSUE TITLE
Vnašanje slik

### ISSUE THREAD

**Issue by MarinaUVP** [MarinaUVP/Pristanisce#1]
Težava, ker noče prikazati slike Logo_pristanisce.png. Slika se nahaja v mapi views v datoteki glavna.html.
Morda je težava v {{!base}}, %rebase?!

**Comment by jaanos** [comment]
Slika je statična vsebina in torej sodi v mapo `static` (lahko npr. naredita znotraj nje mapo za slike). Na sliko se potem sklicujeta tako kot na ostale statične datoteke, npr. `/static/Logo_pristanisce.png` (ustrezno popravita, če bo res v dodatni mapi).

Mimogrede: opažam, da se vama je v mapo `views` izmuznila datoteka `Thumbs.db`. To je datoteka s sličicami, ki jo naredijo Windows, in tako ne sodi na repozitorij. Svetujem, da jo pobrišeta, v `.gitignore` pa dodasta vrstico `Thumbs.db`, tako da je ne bosta več ponesreči dodajala.

**Comment by jakobvalic** [comment]
Hvala lepa za hiter in učinkovit odgovor. Sedaj lahko dodajava slike, Thumbs pa je v .gitignor-u. :)
