### ISSUE TITLE
Slike v zgornji vrstici

### ISSUE THREAD

**Issue by MarinaUVP** [MarinaUVP/Pristanisce#2]
Na vsaki strani imava zgornjo vrstico, kjer sta oz. naj bi bili sliki, ki sta tudi povezavi do glavne strani in strani za administratorja. Sliki sta prikazani v večini primerov, razen na straneh, kjer lahko administrator dodaja podatke v bazo. Ne ugotoviva kje je težava.

**Comment by jaanos** [comment]
Trenutno za sliki uporabljata relativno pot, npr. `static/slike/Logo_majhen_podlaga.png`. Iz strani npr. `/administrator/dodaj_izvedbo_potovanja` bo potem brskalnik sliko iskal pod `/administrator/static/slike/Logo_majhen_podlaga.png`, kjer je seveda ne najde. Rešitev bo, da uporabita absolutno pot - začnita jo torej s `/` (podobno, kot imata za CSS).

**Comment by MarinaUVP** [comment]
Sem uredila. Hvala!
