### ISSUE TITLE
Podajanje spremenljivk

### ISSUE THREAD

**Issue by jakobvalic** [MarinaUVP/Pristanisce#3]
Lep pozdrav.
Imam nekaj spremenljivk, ki jih želim prenesti na naslednjo stran, ko uporabnik pritisne gumb. Problem je, da teh spremenljivk ne morem podati kot argument lastnosti `value`, npr.` value="{{zacetek_potovanja}}"`. Tudi na spodnji sliki prikazan java-script ne deluje. 
Hvala za odgovor. 
![podajanje_spremenljivk](https://user-images.githubusercontent.com/22883056/39157332-ac913bbe-475a-11e8-8236-76581ba00886.png)

**Comment by jaanos** [comment]
Kar rabita na tem mestu prenesti naprej, je ID potovanja in število vozovnic - ostale podatke lahko dobita s poizvedbo glede na ID. Prenos števila vozovnic pri meni deluje (sem ga poskusil v `kupiVozovnico` pridobiti iz `request.forms.stevilo_vozovnic`). Za ID bo deloval pristop s skritim poljem - pazita le, da dasta vrednost atributa v navednice (npr. `value="{{id}}"`). Vstavljanje polja z JavaScriptom tako ne bo potrebno.

Tako uporabnik tudi ne bo mogel podtakniti svojih podatkov - vse, kar morata preveriti, je to, da izbrani ID obstaja, ter da je število vozovnic v dovoljenem rangu.
