### ISSUE TITLE
"NOT IN (SELECT ...)"  v SQL poizvedbah v Pythonu ne deluje

### ISSUE THREAD

**Issue by jakobvalic** [MarinaUVP/Pristanisce#4]
Še nekaj me zanima. 
Napisan imam ukaz, ki deluje v SQLiteStudiu, ne deluje pa, iz python datoteke. Glavni `SELECT `stavek in pomožni `SELECT `stavek delujeta pravilno, ko oba zložimo skupaj z `NOT IN` veznikom, pa javi  `Syntax error near ","`.
Na spodnjem primeru je prva funkcija v `modeli.py`, kjer sem želel uporabiti ukaz. Ker ni delal, sem stvar obšel z nekaj dela s seznami, kot je razvidno v drugi funkciji. Zanima me samo, zakaj prva varianta (SQL poizvedba) ni učinkovita. Je to ena od omejitev SQL poizvedb v Pythonu?
Hvala za odgovor.

![slika](https://user-images.githubusercontent.com/22883056/39316875-8889581a-497a-11e8-8e06-dc81b7f3e919.png)

**Comment by jaanos** [comment]
Sumim, da Python in SQLiteStudio uporabljata različne verzije knjižnice za SQLite - pri meni v SQLiteStudio 3.03 namreč prav tako taka poizvedba ne deluje (očitno *n*-terice niso podprte).

Ekvivalentno poizvedbo je mogoče doseči z `LEFT JOIN`:
```sql
SELECT naziv_potovanja, tip
FROM Nacrt_poti JOIN Tip_kabine
LEFT JOIN Cena_kabine
ON Nacrt_poti.id = Cena_kabine.id_nacrt_poti
AND Tip_kabine.id = Cena_kabine.id_tip_kabine
WHERE Cena_kabine.id_nacrt_poti IS NULL
```

Mimogrede, opazil sem, da v tabelah `Cena_kabine`, `Ima_odsek` in `Ima_vozovnico` nimata glavnih ključev. V vsaki od teh tabel kot glavni ključ nastavita obe referenci skupaj (v `Cena_kabine` potem ne potrebujeta `UNIQUE`).
